### ISSUE TITLE
nuscenes_occ_infos_train.pkl

### ISSUE THREAD

**Issue by M0L4N** [wzzheng/PointOcc#2]
Thanks for your work！Could I have the occ pickle files for study？

**Comment by zuosc19** [comment]
We evaluate the occupancy performance of our method on the OpenOccupancy benchmark, and please refer to [OpenOccupancy](https://github.com/JeffWang987/OpenOccupancy) for occupancy data preparation.

**Comment by M0L4N** [comment]
I get it , thx.
